# Generated by Django 4.2.11 on 2024-07-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_moves_forbidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='moves',
            name='belt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='learn.belt'),
        ),
    ]
